export enum ErrorEnum {
  DEFAULT = '0: Lỗi không xác định',
  SERVER_ERROR = '500: Máy chủ đang bận, vui lòng thử lại sau',

  SYSTEM_USER_EXISTS = '1001: Người dùng hệ thống đã tồn tại',
  INVALID_VERIFICATION_CODE = '1002: Mã xác minh không chính xác',
  INVALID_USERNAME_PASSWORD = '1003: Tên đăng nhập hoặc mật khẩu không đúng',
  NODE_ROUTE_EXISTS = '1004: Đường dẫn node đã tồn tại',
  PERMISSION_REQUIRES_PARENT = '1005: Quyền cần phải có node cha',
  ILLEGAL_OPERATION_DIRECTORY_PARENT = '1006: Thao tác bất hợp pháp: Node này chỉ hỗ trợ cha là thư mục',
  ILLEGAL_OPERATION_CANNOT_CONVERT_NODE_TYPE = '1007: Thao tác bất hợp pháp: Không thể chuyển đổi loại node',
  ROLE_HAS_ASSOCIATED_USERS = '1008: Vai trò đang liên kết với người dùng, vui lòng xóa người dùng liên kết trước',
  DEPARTMENT_HAS_ASSOCIATED_USERS = '1009: Phòng ban đang liên kết với người dùng, vui lòng xóa người dùng liên kết trước',
  DEPARTMENT_HAS_ASSOCIATED_ROLES = '1010: Phòng ban đang liên kết với vai trò, vui lòng xóa vai trò liên kết trước',
  PASSWORD_MISMATCH = '1011: Mật khẩu cũ không khớp với mật khẩu hiện tại',
  LOGOUT_OWN_SESSION = '1012: Nếu muốn đăng xuất chính mình, vui lòng sử dụng nút thoát ở góc phải trên',
  NOT_ALLOWED_TO_LOGOUT_USER = '1013: Không được phép đăng xuất người dùng này',
  PARENT_MENU_NOT_FOUND = '1014: Không tìm thấy menu cha',
  DEPARTMENT_HAS_CHILD_DEPARTMENTS = '1015: Phòng ban có phòng ban con, vui lòng xóa các phòng ban con trước',
  SYSTEM_BUILTIN_FUNCTION_NOT_ALLOWED = '1016: Không được phép thao tác chức năng hệ thống tích hợp',
  USER_NOT_FOUND = '1017: Không tìm thấy người dùng',
  UNABLE_TO_FIND_DEPARTMENT_FOR_USER = '1018: Không thể xác định phòng ban của người dùng hiện tại',
  DEPARTMENT_NOT_FOUND = '1019: Không tìm thấy phòng ban',
  PARAMETER_CONFIG_KEY_EXISTS = '1022: Khóa cấu hình tham số đã tồn tại',
  DEFAULT_ROLE_NOT_FOUND = '1023: Vai trò mặc định được gán không tồn tại',

  INVALID_LOGIN = '1101: Phiên đăng nhập không hợp lệ, vui lòng đăng nhập lại',
  NO_PERMISSION = '1102: Không có quyền truy cập',
  ONLY_ADMIN_CAN_LOGIN = '1103: Chỉ quản trị viên mới có thể đăng nhập',
  REQUEST_INVALIDATED = '1104: Yêu cầu hiện tại không còn hiệu lực',
  ACCOUNT_LOGGED_IN_ELSEWHERE = '1105: Tài khoản của bạn đã đăng nhập ở nơi khác',
  GUEST_ACCOUNT_RESTRICTED_OPERATION = '1106: Tài khoản khách không được phép thực hiện thao tác này',
  REQUESTED_RESOURCE_NOT_FOUND = '1107: Không tìm thấy tài nguyên yêu cầu',

  TOO_MANY_REQUESTS = '1201: Yêu cầu quá nhiều, vui lòng thử lại sau 1 phút',
  MAXIMUM_FIVE_VERIFICATION_CODES_PER_DAY = '1202: Mỗi ngày chỉ được gửi tối đa 5 mã xác minh',
  VERIFICATION_CODE_SEND_FAILED = '1203: Gửi mã xác minh thất bại',

  INSECURE_MISSION = '1301: Nhiệm vụ không an toàn, cần đảm bảo có chú thích @Mission',
  EXECUTED_MISSION_NOT_FOUND = '1302: Không tìm thấy nhiệm vụ đã thực thi',
  MISSION_EXECUTION_FAILED = '1303: Thực thi nhiệm vụ thất bại',
  MISSION_NOT_FOUND = '1304: Không tìm thấy nhiệm vụ',

  // Liên quan đến OSS
  OSS_FILE_OR_DIR_EXIST = '1401: Tệp hoặc thư mục đã tồn tại',
  OSS_NO_OPERATION_REQUIRED = '1402: Không cần thực hiện thao tác',
  OSS_EXCEE_MAXIMUM_QUANTITY = '1403: Đã vượt quá số lượng xử lý tối đa được hỗ trợ',
}
